name: .net

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '5.x' # The .NET SDK version to use
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: |
        cd ./dotnet/SimpleSauce.Test
        dotnet restore --verbosity normal
    - name: Build
      run: |
        cd ./dotnet/SimpleSauce.Test
        dotnet build --configuration Release --no-restore --verbosity normal
    - name: Test
      run: |
        cd ./dotnet/SimpleSauce.Test
        dotnet test --no-restore --verbosity normal