name: dotnet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: |
          cd ./dotnet/SimpleSauce.Test
          dotnet restore
      - name: Build
        run: |
          cd ./dotnet/SimpleSauce.Test
          dotnet build --configuration Release --no-restore
      - name: Test
        run: |
          cd ./dotnet/SimpleSauce.Test
          dotnet test --no-restore --verbosity normal